### ISSUE TITLE
break out board? 

### ISSUE THREAD

**Issue by yangxing844** [WSTRN/LPM009M360_demo#1]
hi, I am trying to light this display in zmk, I know that you have successfully done that,  and I am using a custom breakout board with MOSI, SCK, VCC, GND, CS pinout, which is compatible with nice!view, however I wasn't able to use the driver in zmk nor in this repo to perform simplest operation like CMD_ALL_CLEAR, all I get is some times blacnk screen, mostly the screen is displaying static,  I see that you have configured the MISO pin, this lets me wonder whether I am missing something in my breakout board, so I would like to reach out and ask how are you wiring the pins to the display? maybe the breakout board wuold be nice, Thank you very much!

**Comment by WSTRN** [comment]
Hi yangxing,
This repo is only for zephyrRTOS because zmk uses an early version of zephyr. if you want to use the LPM009M360 display in zmk, you can check out: https://github.com/WSTRN/zmk. This repo contains the display driver, then you may find some help here: https://github.com/WSTRN/DUC_KB_BPad10 to write the configuration file.

about hardware:
driving this display you need at least 6 pins: VCC GND MOSI SCK CS DISP, please ignore MISO.

if you still have some trouble, feel free to ask me.

cheers

**Comment by yangxing844** [comment]
Hi Will!
thanks for taking the time,reading from your replay  I think i may know the culprit of the not working display problem, I dont have a disp pin, I wired it directly to vcc, reading from the datasheet, it seems that some delay between VCC ON and DISP ON is required, is that so?  I will order another pcb and test, again thank you very much!!!

2024年6月11日 下午11:37:59 Will ***@***.***>:

**Comment by WSTRN** [comment]
From the datasheet, it requires 1ms after the power supply rising. But, in my opinion, DISP is like a switch, it just controls the on and off of the display. Directly connecting to the VCC should work, maybe you can also focus on other potential issues. Just a suggestion, hope you can do it!

**Comment by yangxing844** [comment]
hi, after change the breakout board, disconnecting DISP from VCC, the screen is able to work! and it seems DISP can not be directly connect to VCC, at least not without some delay, thank you for your patience!
